### PR TITLE
Add features required for Jitsi Meet 7830 and newer

### PR DESCRIPTION
**Pull request by spijet**
As described in #59, Jitsi Meet 7830 introduces a couple of new things that make it incompatible with this chart. To name a few:
* JVB now expects a list of IP addresses to advertise in `JVB_ADVERTISE_IPS` instead of one public IP in `DOCKER_HOST_ADDRESS`;
* Jitsi Web service now has broken non-FQDN resolution, so we have to use FQDN-like service names until it's fixed;
* (an extension of previous point) Jitsi Web service now has to know about the cluster's DNS service IP at all times, not just in some edge cases;
* Jibri now uses it's own PulseAudio daemon instead of relying on ALSA-powered host loopback audio module (`snd_aloop`).

This PR addresses all of these issues. I've been using this branch locally for a couple of weeks now and everything works perfectly fine. As a bonus, we can now easily scale out Jibri instances, thanks to that built-in PulseAudio daemon. :)

### CODE REVIEW

**Comment by sapkra** [comment]
@spijet I'm not sure how to review it, because I'm not really up-to-date with the latest changes of Jitsi and I'm also not using Jitsi anymore. I think you already have to permissions to merge it and create releases. Feel free to do so. 🚀

**Comment by spijet** [comment]
@saghul, maybe you have any comments or additions to this?

If not, I'll merge the PR and prepare a new release in a day or two. :)

**Comment by saghul** [comment]
No comments, go for it!

**Comment by saghul** [comment]
FWIW I think I have fixed the resolution now (latest commit in master in docker-Jitsi-meet).

It would be nice if you can give it a try!

**Review by sapkra — APPROVED** [review]

**Comment by spijet** [comment]
Thanks for the merge! Sorry I didn't merge it earlier. I suppose the only things left are to bump the chart version and package the release?

**Comment by saghul** [comment]
Go for it!

**Comment by spijet** [comment]
Aaaand it's done! Well, if I didn't miss anything that is. :)

**Pull request merged**
